name: smscsim-main-build

on:
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GOPRIVATE: "github.com/juphoon/*"
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  AWS_DEFAULT_REGION: ap-east-1 # This is the region where the ECR server is located.
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # This workflow contains a single job called "upload"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout codes.
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Pack up artifacts for the release.
      - name: Pack Release Artifacts
        run: |
          zip --junk-paths smscsim bin/*
      # Upload artifacts for the release.
      - name: Upload Release Artifacts
        id: upload-release-artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./smscsim.zip
          asset_name: smscsim.zip
          asset_content_type: application/zip