name: run-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Run Golang tests
        run: go test

